# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


production:
  census_key: 778051d4e0bd2daff263071145cfe3b9b452ae71
  twitter_consumer_key: '0QMs8yFkqsRJAllcPSn7Az1sb'
  twitter_consumer_secret: 'd3bX0bCvk75ZPOFrfHdydqh3VDZJECM6jdm9k8yZzdXPcjc9u2'
  twitter_access_token: '42666466-tVRCC7uvz9z94D4ChAPOiyD0anNgptAmWNk1WU9pr'
  twitter_access_token_secret: 'OuJEdbk7YdVbipOpXbxZ00vGmQv9IH4RDaHMtz8hFkVcI'

development:
  census_key: 778051d4e0bd2daff263071145cfe3b9b452ae71
  twitter_consumer_key: '0QMs8yFkqsRJAllcPSn7Az1sb'
  twitter_consumer_secret: 'd3bX0bCvk75ZPOFrfHdydqh3VDZJECM6jdm9k8yZzdXPcjc9u2'
  twitter_access_token: '42666466-tVRCC7uvz9z94D4ChAPOiyD0anNgptAmWNk1WU9pr'
  twitter_access_token_secret: 'OuJEdbk7YdVbipOpXbxZ00vGmQv9IH4RDaHMtz8hFkVcI'

test:
  census_key: 778051d4e0bd2daff263071145cfe3b9b452ae71
  twitter_consumer_key: '0QMs8yFkqsRJAllcPSn7Az1sb'
  twitter_consumer_secret: 'd3bX0bCvk75ZPOFrfHdydqh3VDZJECM6jdm9k8yZzdXPcjc9u2'
  twitter_access_token: '42666466-tVRCC7uvz9z94D4ChAPOiyD0anNgptAmWNk1WU9pr'
  twitter_access_token_secret: 'OuJEdbk7YdVbipOpXbxZ00vGmQv9IH4RDaHMtz8hFkVcI'
